<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publish</name>
   <tag></tag>
   <elementGuidId>9ab5e8ba-db7f-4ca6-9cc8-085cf0b91965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_obv.shell._surface_1725766791965']/div/div[2]/div[2]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button--primary.button--filled.button--smaller.button--withChrome.u-accentColor--buttonNormal.button--publish.js-publishButton.js-buttonRequiresPostId.u-paddingLeft10.u-paddingRight10.button--chromeless.js-buttonDisabledPrimary.is-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Publish&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1008ccea-8713-4beb-9afc-8de7f1ae3e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary button--filled button--smaller button--withChrome u-accentColor--buttonNormal button--publish js-publishButton js-buttonRequiresPostId u-paddingLeft10 u-paddingRight10 button--chromeless js-buttonDisabledPrimary is-touched</value>
      <webElementGuid>56cc53ee-895a-433f-baba-286d85c78e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>show-prepublish</value>
      <webElementGuid>21d45da6-5fd1-4482-bb42-3491ed9e4c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-source</name>
      <type>Main</type>
      <value>post_edit_prepublish</value>
      <webElementGuid>a4d20bd8-e8ed-4844-9651-c4decbbe2e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>757bd268-440d-4152-8b6c-1ab90bcec8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_obv.shell._surface_1725766791965&quot;)/div[@class=&quot;screenContent surface-content is-showingDrawer&quot;]/div[@class=&quot;metabar u-clearfix u-fixed u-backgroundTransparentWhiteDarkest u-xs-sizeFullViewportWidth js-metabar&quot;]/div[@class=&quot;js-metabarMiddle metabar-inner u-marginAuto u-maxWidth1032 u-flexCenter u-justifyContentSpaceBetween u-height65 u-xs-height56 u-paddingHorizontal20&quot;]/div[@class=&quot;metabar-block u-flex0 u-flexCenter&quot;]/div[@class=&quot;u-flexCenter u-height65 u-xs-height56 u-paddingLeft8 u-paddingRight8&quot;]/button[@class=&quot;button button--primary button--filled button--smaller button--withChrome u-accentColor--buttonNormal button--publish js-publishButton js-buttonRequiresPostId u-paddingLeft10 u-paddingRight10 button--chromeless js-buttonDisabledPrimary is-touched&quot;]</value>
      <webElementGuid>4a94a6da-9f73-40da-94e3-0dee4ea421d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_obv.shell._surface_1725766791965']/div/div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>ccc315b2-b12a-4376-b9b8-c03478b88cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved'])[1]/following::button[1]</value>
      <webElementGuid>ff66d2ec-dd34-4e8c-8052-215ecc792052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Understanding Grid in Web Design: A Key to Creating Structured and Balanced Layouts'])[1]/preceding::button[4]</value>
      <webElementGuid>74f5c089-15af-4fd0-9741-c5fdc7d5a07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>31d20244-1d46-4a13-b7ae-807304d5285f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>3179d8c3-dd0f-4986-8343-88ccf17ffa3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
