<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Publish_editor_7</name>
   <tag></tag>
   <elementGuidId>be4319b0-086e-4ac1-ab3d-5e5f62ae1161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editor_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;editor_7&quot;]/section/div[2]/div/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#editor_7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55818f1b-e754-4928-9fad-06ab561179e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>postArticle-content js-postField js-notesSource editable</value>
      <webElementGuid>4a6d40b7-643a-4350-9e8f-bdbb45072b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editor_7</value>
      <webElementGuid>6ee6ce37-2704-4697-92c5-124b4c3e9bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>g_editable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f7af1a3-f3d7-40f4-ac43-580770605077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>54216bb0-f364-49f8-b719-42f27f626b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a9feea7-2eda-4664-9641-65402467faf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-default-value</name>
      <type>Main</type>
      <value>Title
Tell your story…</value>
      <webElementGuid>77e30ac5-cc1f-4e4d-978c-cddc586b6878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editor_7&quot;)</value>
      <webElementGuid>633a5fda-437a-415a-a1bf-c338f7e40ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='editor_7']</value>
      <webElementGuid>52454258-d2ac-47fd-ac37-389ff207323d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_obv.shell._surface_1725766791965']/div/main/article/div</value>
      <webElementGuid>00475ba9-7be3-4f12-904b-f7b7656c6c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[1]/following::div[5]</value>
      <webElementGuid>5408d050-ca02-44a1-a6ce-43f876207dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::div[7]</value>
      <webElementGuid>20bca15b-9a1b-47c5-954b-bfa540b0c710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div</value>
      <webElementGuid>15e7ffc9-8948-476a-b611-7d335e22dd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'editor_7']</value>
      <webElementGuid>ccdb30ac-1b05-49b9-8589-833d6a2b5f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
