<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Respond</name>
   <tag></tag>
   <elementGuidId>5c9bb8e0-8efd-43a9-ab92-bd52b7dace4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ar.b.aq.am.abi.kl.abj.abk.abl.abm.abn.kr.ks.fz.abo.abp.kw.kx.u.cs.bz.ky.kz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;ResponseRespondButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8464e99-5431-4cab-b05f-b7324968a2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ar b aq am abi kl abj abk abl abm abn kr ks fz abo abp kw kx u cs bz ky kz</value>
      <webElementGuid>6ad9c27d-9dc5-46f0-b804-2b23b12a6fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ResponseRespondButton</value>
      <webElementGuid>8a4b2b03-95e3-4539-93fe-2888759ef208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Respond</value>
      <webElementGuid>b79bab11-4fbe-46de-acec-e3407a80b285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;zo&quot;]/div[@class=&quot;ach acd aci acj ack acb ba cs acl acm acn mn aja acp ajb acr acs act acu ajc acw&quot;]/div[2]/div[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;ug&quot;]/div[@class=&quot;bb dp x&quot;]/div[@class=&quot;acj akz mh n fb amf amg alc&quot;]/div[@class=&quot;n fb&quot;]/div[@class=&quot;do ali ao n akw mn ame&quot;]/div[@class=&quot;akv lj n akw mn ame&quot;]/button[@class=&quot;ar b aq am abi kl abj abk abl abm abn kr ks fz abo abp kw kx u cs bz ky kz&quot;]</value>
      <webElementGuid>96e4af28-ad12-484c-b0d0-f3063dab9254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>87ff5272-6efc-4730-b95c-9bfe4f01d6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>48a08311-4e11-44c6-b3bb-7842c1cb9469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='good'])[1]/following::button[2]</value>
      <webElementGuid>a33e2650-9fc1-413b-b25e-d5c0db4bd2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Most relevant'])[1]/preceding::button[1]</value>
      <webElementGuid>3520b72f-a197-415a-8ce6-361935e039ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::button[5]</value>
      <webElementGuid>59191f5a-cca1-4c08-b24a-b12157081942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Respond']/parent::*</value>
      <webElementGuid>050baff7-bf00-478d-9c7c-bb885629769e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>c41ed271-cef9-4386-9768-bb4175b76b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Respond' or . = 'Respond')]</value>
      <webElementGuid>a0b3542b-cdb5-4321-ad23-826f1b83865e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
