<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>173eb06a-2949-4e14-8b05-ec0be3f20163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alj.x > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bde285b9-bac0-4388-9d0d-40f67040c466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6ce4ba56-2b9d-42ba-a80c-dfa9e17ccc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a58dec3b-e0c2-4078-be4f-45d09bb6a71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slate-editor</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d226cee-c5e8-489b-b1a7-4b50705fcc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slate-node</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>f7814ce3-444e-4c0d-821e-f04d7c4c5880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3851cb40-f679-4a35-9d5e-1624b4e26a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6c5bbeb1-b760-4a8e-a5f1-c572893c9c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;zo&quot;]/div[@class=&quot;ach acd aci acj ack acb ba cs acl acm acn mn aja acp ajb acr acs act acu ajc acw&quot;]/div[2]/div[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;ug&quot;]/div[@class=&quot;bb dp x&quot;]/div[@class=&quot;acj akz mh n fb amf amg alc&quot;]/div[@class=&quot;n fb&quot;]/div[@class=&quot;alf amj alh&quot;]/div[@class=&quot;alj x&quot;]/div[1]</value>
      <webElementGuid>af7a911d-02e2-4913-bd60-adf95d32fd2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>111dac58-aea3-49c8-b824-f70eb42d0ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rakha Putra Pratama'])[1]/following::div[4]</value>
      <webElementGuid>924c3394-1e29-45c5-9750-bc0e6a5652ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses (36)'])[1]/following::div[21]</value>
      <webElementGuid>381c3126-083b-46f8-b0a3-125482633fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[7]</value>
      <webElementGuid>ab667fc6-5880-4bce-af19-e536e130564f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>66c3ff96-1730-4565-a9a9-a2e1728dd2f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
