<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Respond</name>
   <tag></tag>
   <elementGuidId>2232db19-e280-49c9-a810-75471b0c69c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ar.b.aq.am.aln.kv.alo.aoz.apa.apb.apc.md.le.fz.apd.ape.li.lj.u.cs.bz.lk.ll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div[2]/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;ResponseRespondButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e318ecef-0687-4d42-a2e5-66357b996005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ar b aq am aln kv alo aoz apa apb apc md le fz apd ape li lj u cs bz lk ll</value>
      <webElementGuid>abd1d964-3050-4542-9e7f-97d07d55687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ResponseRespondButton</value>
      <webElementGuid>234ad3b4-91af-461f-836f-2aca733c1db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Respond</value>
      <webElementGuid>3b5e5fe8-e0d5-4e13-b395-16e5cc4416c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;aev&quot;]/div[@class=&quot;agk agg agl agm agn age ba cs ago agp agq mn ama ags amb agu agv agw agx amc agz&quot;]/div[2]/div[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;wo&quot;]/div[@class=&quot;bb dp x&quot;]/div[@class=&quot;agm aoi lm n fb apu apv aol&quot;]/div[@class=&quot;n fb&quot;]/div[@class=&quot;do aor ao n aof mn apt&quot;]/div[@class=&quot;aoe ki n aof mn apt&quot;]/button[@class=&quot;ar b aq am aln kv alo aoz apa apb apc md le fz apd ape li lj u cs bz lk ll&quot;]</value>
      <webElementGuid>87707cdc-5f6c-46df-8412-0485ec4eb953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>dd548174-75f6-48da-93ae-e64f431b25fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>c673cc2f-e65c-437a-8d50-03259f490fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yes'])[1]/following::button[2]</value>
      <webElementGuid>809e900f-c931-414b-b2e8-3217ab8e7103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Most relevant'])[1]/preceding::button[1]</value>
      <webElementGuid>f9064318-538d-4cec-ade3-ae1ae734a064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swift Package Manager'])[1]/preceding::button[3]</value>
      <webElementGuid>b28a511f-f16d-4a85-9e97-402f2d87e6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Respond']/parent::*</value>
      <webElementGuid>ea73a179-189f-4d1f-8017-7e502a2e1ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>350dce1b-0d78-4676-95b5-2ec58a2e5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Respond' or . = 'Respond')]</value>
      <webElementGuid>e9697079-5b2a-4d17-b499-56ed13b83a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
