<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>45850095-b3d0-454f-bfe6-dc25134ef4f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.aos.x > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div[2]/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[1]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>701d29d2-89b2-426f-a824-214110b52134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f8e3b626-0a3d-4ace-9729-d5b69d942e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba5c9d6d-56c5-41bc-9ca1-fc9f1eab8e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slate-editor</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ee49fe5-a3a6-4a45-a57c-6bc656212416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slate-node</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>ed5ff81b-c736-4047-8525-2d0df2c12d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22cd4aba-3bb7-4c97-a647-53cd9ec1a661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>07ce1a91-d23b-4024-acfa-0f64bef1fd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;aev&quot;]/div[@class=&quot;agk agg agl agm agn age ba cs ago agp agq mn ama ags amb agu agv agw agx amc agz&quot;]/div[2]/div[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;wo&quot;]/div[@class=&quot;bb dp x&quot;]/div[@class=&quot;agm aoi lm n fb apu apv aol&quot;]/div[@class=&quot;n fb&quot;]/div[@class=&quot;aoo apy aoq&quot;]/div[@class=&quot;aos x&quot;]/div[1]</value>
      <webElementGuid>78f5ee39-ac27-4fad-b981-fd7793961deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>00ba09ac-0796-4d2c-b7a4-7ccc07a9c16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rakha Putra Pratama'])[1]/following::div[4]</value>
      <webElementGuid>f70638ad-4ea4-4ab2-83f3-131c54433735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses (22)'])[1]/following::div[21]</value>
      <webElementGuid>eabfa337-fa2d-4973-8b2f-7f5d84e40677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[7]</value>
      <webElementGuid>35946389-6e83-4ef2-9845-8982f67c5e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>ccb172c3-5c22-4329-8589-b24ac641d6fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
