<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_yes</name>
   <tag></tag>
   <elementGuidId>7252e7a1-53ea-49e1-b91d-f7c648b319fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div[2]/div[4]/div/div[11]/div/div/div/div[2]/pre/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;yes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fed1d02-3fa8-4d76-8bbf-23a165bd12a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wo</value>
      <webElementGuid>6ebe3140-c7e4-440c-87be-6614981605b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>0a99364a-377b-47a8-a47f-2931d39fc1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;aev&quot;]/div[@class=&quot;agk agg agl agm agn age ba cs ago agp agq mn ama ags amb agu agv agw agx amc agz&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;x&quot;]/div[@class=&quot;jf afc jg x&quot;]/div[1]/div[@class=&quot;m ba&quot;]/div[@class=&quot;fm amz x&quot;]/div[@class=&quot;ano x kf&quot;]/pre[@class=&quot;wy&quot;]/div[@class=&quot;anp x&quot;]/div[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;wo&quot;]</value>
      <webElementGuid>124099b8-b373-4861-95dc-fdd664e3d4c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div[2]/div[4]/div/div[11]/div/div/div/div[2]/pre/div/div/div</value>
      <webElementGuid>3fc9635f-1628-4229-81b5-7faee2f0d547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You'])[1]/following::div[4]</value>
      <webElementGuid>a9498717-474f-41b4-bb0b-6d2b2a7f38cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[10]/following::div[20]</value>
      <webElementGuid>4ccb499f-24b4-41dd-9504-f8a706ed87ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[11]/preceding::div[9]</value>
      <webElementGuid>882282d8-b247-4948-a8a5-bd9eeddf0c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are those little videos basically Gifs? I didnt know we can do that on here!'])[1]/preceding::div[22]</value>
      <webElementGuid>acce41a3-0f9c-49c0-8eed-5f7d389d0a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yes']/parent::*</value>
      <webElementGuid>f64c2606-0512-4f78-ae99-b5ef72fc55bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/pre/div/div/div</value>
      <webElementGuid>3634c560-d4ff-4454-a1c1-5e4914390c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'yes' or . = 'yes')]</value>
      <webElementGuid>338818c6-242d-4e56-913d-fc126f0c38d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
