<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Whats new in Flutter 3.24</name>
   <tag></tag>
   <elementGuidId>77d86082-5b63-4f07-a646-b4ecad221ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='fb28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fb28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;storyTitle&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a4b4391f-f97f-4e17-b3ab-eccc5441c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fb28</value>
      <webElementGuid>ff3b07c5-f907-49f5-bf7a-01d060d55f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pw-post-title vr fp vs ar gw vt vu vv vw vx vy vz wa ss wb st sv sw wc sx sz ta wd tb td we bx</value>
      <webElementGuid>d5d98396-563d-45eb-8471-745972ac4ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>storyTitle</value>
      <webElementGuid>7355a36b-92d7-422a-a020-6ae6c5b2be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What’s new in Flutter 3.24</value>
      <webElementGuid>8d86cdd2-83e2-4477-9346-277977635325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fb28&quot;)</value>
      <webElementGuid>62dbc84a-f600-4321-8754-4320eeec36e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='fb28']</value>
      <webElementGuid>eff1db18-3d1f-4307-b321-a040863c8698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[3]/article/div/div/section/div/div[3]/div/div/div/h1</value>
      <webElementGuid>bfc29712-f8e9-4635-b307-ebe2b22005be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top highlight'])[1]/following::h1[1]</value>
      <webElementGuid>9cef5baa-d224-42fa-8c9c-640fbe7c2945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a member'])[2]/following::h1[1]</value>
      <webElementGuid>6477000d-1ac8-4605-a198-46c3c32bf555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unleashing Flutter GPU, Multi-View Embedding, and More'])[1]/preceding::h1[1]</value>
      <webElementGuid>e24993b9-b4fd-4a62-8486-de94f092c925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kevin Chisholm'])[1]/preceding::h1[1]</value>
      <webElementGuid>c9e41fb6-4d52-42d8-9bc6-aea994a19a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='What’s new in Flutter 3.24']/parent::*</value>
      <webElementGuid>8ac7867a-4cd2-483c-bb34-a8f814626779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>dd67860c-b998-4f43-9372-3e97a0c9725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'fb28' and (text() = 'What’s new in Flutter 3.24' or . = 'What’s new in Flutter 3.24')]</value>
      <webElementGuid>fe534151-01cb-43a1-b770-41b322dd95fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
