<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>018d3b26-8b5a-4297-9e87-e84c2802dd6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cq.b.cr.cs.cv.cw.cx.cy.cz.da.db.dc.dd.de.df.dg.dh.jc.di.u.dj.dk.dl.dm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07b672c8-4a7d-4861-b484-d1be4d879d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq b cr cs cv cw cx cy cz da db dc dd de df dg dh jc di u dj dk dl dm</value>
      <webElementGuid>5ab3d624-7d45-403b-b98b-ed3762172b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>39bcf29b-98c6-4f4c-bb73-7ade0d44dc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p fr fs ft fu fv fw bd be ez bf bg fx&quot;]/div[@class=&quot;fy fz ga gb gc gd&quot;]/div[@class=&quot;pw-susi-modal ge gf gg gh gi gj gk gl gm gn go gp gq gr bt az gs&quot;]/div[@class=&quot;gt dn m gu n bs gv gw gx gy gz&quot;]/div[@class=&quot;ha hb n o x p ay dm hc hd gy&quot;]/div[@class=&quot;hj bt&quot;]/div[@class=&quot;n o x&quot;]/div[@class=&quot;jb hv bt&quot;]/button[@class=&quot;cq b cr cs cv cw cx cy cz da db dc dd de df dg dh jc di u dj dk dl dm&quot;]</value>
      <webElementGuid>5de837ba-1613-464e-858b-a2301b8652bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email'])[1]/following::button[1]</value>
      <webElementGuid>d4802150-34df-492e-bb77-93f5443cbf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the email address associated with your account, and we’ll send a magic link to your inbox.'])[1]/following::button[1]</value>
      <webElementGuid>c8266b61-52fa-4dc7-9439-48cb1190ae49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with Google'])[1]/preceding::button[1]</value>
      <webElementGuid>cfd02f66-729c-45e3-b01e-b5f9160006b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All sign in options'])[1]/preceding::button[1]</value>
      <webElementGuid>f1ee3593-8c57-4dbb-b240-5d01815e0801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>05f472e1-5886-453f-9240-cd622c0795e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>e44706c0-5abf-466d-8732-9150db8becb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>536bb752-8416-461d-a988-3525d51a1f3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
