<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email_iu by bw ca iv iw ix iy iz ja</name>
   <tag></tag>
   <elementGuidId>9dc8e3ad-a8a7-4729-9ca2-acdc8a045f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='m']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.iu.by.bw.ca.iv.iw.ix.iy.iz.ja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9715ff4-0fd4-4a7a-82cc-d5452bec308d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iu by bw ca iv iw ix iy iz ja</value>
      <webElementGuid>5fd642ab-e259-498b-ab6f-83e0139293aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d54b3e24-3f5a-4bd0-96e4-9f6fcb794b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>2e3f4aad-3a44-4398-998e-db937a565316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>m</value>
      <webElementGuid>911cf299-0782-4e4d-8106-0a08c83bfd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p fr fs ft fu fv fw bd be ez bf bg fx&quot;]/div[@class=&quot;fy fz ga gb gc gd&quot;]/div[@class=&quot;pw-susi-modal ge gf gg gh gi gj gk gl gm gn go gp gq gr bt az gs&quot;]/div[@class=&quot;gt dn m gu n bs gv gw gx gy gz&quot;]/div[@class=&quot;ha hb n o x p ay dm hc hd gy&quot;]/div[@class=&quot;hj bt&quot;]/div[@class=&quot;n o x&quot;]/div[@class=&quot;im hv bt&quot;]/span[@class=&quot;cq b cr cs ct&quot;]/div[@class=&quot;io n x&quot;]/div[@class=&quot;n io u di gt ip hl je is it&quot;]/input[@class=&quot;iu by bw ca iv iw ix iy iz ja&quot;]</value>
      <webElementGuid>c2b6246a-ee78-441a-a99f-354d8e57c14f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='m']</value>
      <webElementGuid>e0fb2a1c-e971-4e42-aaf3-32dfb5c4c1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>998bd045-9479-4599-b962-ef734f070d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email']</value>
      <webElementGuid>058d9fbd-c39a-400e-b5a9-25333c4d3a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
