<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create new list_wx bh bf bi wy wz xa _e93dd3</name>
   <tag></tag>
   <elementGuidId>d8b64efe-5400-4461-9f6a-450d003ae583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.wx.bh.bf.bi.wy.wz.xa.xb.by.xc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;creatListModalInput&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99f0311e-eb37-457b-953a-6488f8c540d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wx bh bf bi wy wz xa xb by xc</value>
      <webElementGuid>5ccda909-6754-4494-af9d-6fbdb7a152a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3785fbe5-48bc-4d14-897d-ca517151e091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give it a name</value>
      <webElementGuid>c1d845c4-05c2-4733-a569-0b0a0d5a4579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>creatListModalInput</value>
      <webElementGuid>d1d69f92-27f3-4b4b-adce-91878ea2ea38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p vr vs vt vu vv vw z vx jy ij vy&quot;]/div[@class=&quot;vo vp vq&quot;]/div[@class=&quot;x cf&quot;]/div[@class=&quot;vz ll wa wb wc n o fb do wd we wf wg wh wi&quot;]/div[@class=&quot;wj wk n o fb p bd wl wm wh&quot;]/div[@class=&quot;n o fb&quot;]/div[@class=&quot;wn x&quot;]/div[@class=&quot;ws x rb wt&quot;]/div[@class=&quot;gh x&quot;]/span[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;m n fb&quot;]/div[@class=&quot;n m u li ll wu qu gy mr ww&quot;]/input[@class=&quot;wx bh bf bi wy wz xa xb by xc&quot;]</value>
      <webElementGuid>3be39037-cdb8-487e-98da-38d0909dd999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>11ebdaa5-9314-4838-8efb-2850cc81352a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/input</value>
      <webElementGuid>203b2152-49b8-4972-8d1c-8c823c5de5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Give it a name']</value>
      <webElementGuid>b765aa57-2aee-4b77-858f-4b028b52b33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
