<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>ae46bf48-87e6-492f-94fd-c4e438c4fa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ar.b.bu.am.lx.mh.ly.wj.wk.wl.wm.md.le.fz.wn.wo.li.lj.u.cs.bz.lk.ll</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;deleteStoryModalConfirmButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2691cd06-2f51-4d39-9943-91ae8370c0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ar b bu am lx mh ly wj wk wl wm md le fz wn wo li lj u cs bz lk ll</value>
      <webElementGuid>3fbca5d3-d039-44de-9c94-cbb025181c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>deleteStoryModalConfirmButton</value>
      <webElementGuid>cdfa2294-b048-4750-935a-a3c552e14d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>df2f33fd-a1b9-4de5-9718-7305f364e3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[@class=&quot;n o p us ut uu uv uw ux z uf jy ij uy&quot;]/div[@class=&quot;up uq ur&quot;]/div[@class=&quot;x cf&quot;]/div[@class=&quot;uz lm va vb vc n o fb do vd ve vf vg vh vi&quot;]/div[@class=&quot;vj vk n o fb p bd vl vm vh&quot;]/div[@class=&quot;n o fb&quot;]/div[@class=&quot;m n p&quot;]/div[@class=&quot;wi bz&quot;]/button[@class=&quot;ar b bu am lx mh ly wj wk wl wm md le fz wn wo li lj u cs bz lk ll&quot;]</value>
      <webElementGuid>ca83b6af-da7f-447c-8872-31675727a45c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>8c9a8a9b-bcea-42e4-9910-1fa29f2417e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>7729cf8c-6541-4e81-b020-3eb7d3d68e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>aefbe3bf-9605-4e3b-841b-f5e8614c6e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>e2196882-922c-480e-9fb7-18d2c06c1609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
