<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>209a4644-cd55-4597-a623-fd324c2499a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pt.h > div.n.oe.oc > button.ar.b.wv.ww.wx.wy.wz.xa.xb.xc.xd.xe.xf.xg.xh.xi.xj.xr.xs.xt.xk.xu.xn.qg.la.fz.xv.xq.le.lf.u.cs.bz.lg.lh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c244c63d-6eb7-4843-915d-3ded92a4a90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ar b wv ww wx wy wz xa xb xc xd xe xf xg xh xi xj xr xs xt xk xu xn qg la fz xv xq le lf u cs bz lg lh</value>
      <webElementGuid>b544e6cb-fda4-4fd4-8a97-366472f003bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>9cd996eb-626c-402b-a3e1-524f6c0f9424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p vx vy vz wa wb gc wc wd z we jy ij wf&quot;]/div[@class=&quot;jd wg wh zn wj wk&quot;]/div[@class=&quot;wl li wm wn x cf c wo wp nq wq wr ws wt&quot;]/div[@class=&quot;pt h&quot;]/div[@class=&quot;n oe oc&quot;]/button[@class=&quot;ar b wv ww wx wy wz xa xb xc xd xe xf xg xh xi xj xr xs xt xk xu xn qg la fz xv xq le lf u cs bz lg lh&quot;]</value>
      <webElementGuid>410e35be-6039-494f-afe5-cf28dacc505b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>b631f279-867d-4975-aaf9-f7e54819f48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Page'])[1]/following::button[2]</value>
      <webElementGuid>3407af92-6e68-428d-bbed-445fb9254ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button[2]</value>
      <webElementGuid>8fedbc0f-cfd0-4f1a-8b3f-f198533e6b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>dd460608-e84f-4a7a-aabd-4b26efbfe76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
