<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_boy</name>
   <tag></tag>
   <elementGuidId>36f78a9c-845a-4473-9f02-70c3b947b75e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='bio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;bio&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;boy&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>291accad-dfe6-45a7-9d35-288ceaca5a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yc bh bf bi yd ye yf yg by jo yh gk yj m</value>
      <webElementGuid>d4440652-0979-484f-8834-d68c8a0c6940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>038c817e-561b-4a44-bcac-d8dcf416b00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bio</value>
      <webElementGuid>cd7cc703-4a95-4b38-9666-948cede47ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>boy</value>
      <webElementGuid>15a0deca-5829-496d-9a46-0b306aabce13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p vx vy vz wa wb gc wc wd z we jy ij wf&quot;]/div[@class=&quot;jd wg wh zn wj wk&quot;]/div[@class=&quot;wl li wm wn x cf c wo wp nq wq wr ws wt&quot;]/div[@class=&quot;pt x&quot;]/span[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;m n fb&quot;]/div[@class=&quot;n m u lf li xz qr gy lr yb&quot;]/textarea[@class=&quot;yc bh bf bi yd ye yf yg by jo yh gk yj m&quot;]</value>
      <webElementGuid>180ba24d-6e45-4554-8ec7-7886f7bfddd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='bio']</value>
      <webElementGuid>ba4c1e44-17a0-4ef0-a0c1-6be88670d0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short bio'])[1]/following::textarea[1]</value>
      <webElementGuid>6d3d59ac-e65d-4499-b87f-c1259651ce49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name*'])[1]/following::textarea[1]</value>
      <webElementGuid>813717f0-507b-43a6-9617-837a4c70fa7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display a link to your X profile'])[1]/preceding::textarea[1]</value>
      <webElementGuid>78fe0e4e-6fc2-4ea8-a561-6cfac938f044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Page'])[1]/preceding::textarea[1]</value>
      <webElementGuid>531d11f4-8b5c-42cf-acf6-ef87f2444f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='boy']/parent::*</value>
      <webElementGuid>086cbfd9-24b1-4ec6-aaf7-1f786a012b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/textarea</value>
      <webElementGuid>64b08edb-676f-488a-8f11-6cabc5acd2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'bio' and (text() = 'boy' or . = 'boy')]</value>
      <webElementGuid>924ae987-ec97-4642-b200-a4a09942d44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
