<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_b</name>
   <tag></tag>
   <elementGuidId>5ab0f5d0-8dcf-436a-86c7-802b6a81bbfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='bio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;bio&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;b&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>983ae8a8-3a94-4996-bb61-16c2b8c1cca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yc bh bf bi yd ye yf yg by jo yh gk yj m</value>
      <webElementGuid>88d3ace9-96b5-4e6e-a415-e03b5503d6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a9bd2583-1e5c-447e-8519-e812c8fba0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bio</value>
      <webElementGuid>2c0ac2e0-e2c5-4cc0-b419-a5422bd448f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>912bc5a9-f07f-4032-a77a-255e9f2bea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p vx vy vz wa wb gc wc wd z we jy ij wf&quot;]/div[@class=&quot;jd wg wh zn wj wk&quot;]/div[@class=&quot;wl li wm wn x cf c wo wp nq wq wr ws wt&quot;]/div[@class=&quot;pt x&quot;]/span[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;m n fb&quot;]/div[@class=&quot;n m u lf li xz qr gy lr yb&quot;]/textarea[@class=&quot;yc bh bf bi yd ye yf yg by jo yh gk yj m&quot;]</value>
      <webElementGuid>fa91f6fc-2cde-4a69-a98f-ca3cf7a2d120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='bio']</value>
      <webElementGuid>78993674-a553-49ed-a229-dec587317283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short bio'])[1]/following::textarea[1]</value>
      <webElementGuid>f9fb26d5-b059-486c-85a5-d4979f3c2647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name*'])[1]/following::textarea[1]</value>
      <webElementGuid>5f2817c9-853e-4598-ba6b-9e72f45ad0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display a link to your X profile'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9ec7a06b-390c-42a3-b0b2-d0abc7b61720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Page'])[1]/preceding::textarea[1]</value>
      <webElementGuid>762210e7-94c7-4dc8-89c2-ffeb891e0082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='b']/parent::*</value>
      <webElementGuid>8b09e81f-7cdc-4a22-a956-0b054be9fe8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/textarea</value>
      <webElementGuid>9ba04b16-176b-41d3-ba32-5fad78f46e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'bio' and (text() = 'b' or . = 'b')]</value>
      <webElementGuid>443ce14c-818b-4d99-baac-4d47f9e7d53c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
