<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_bo</name>
   <tag></tag>
   <elementGuidId>ca60801a-695e-49f6-942f-4b139951f139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='bio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;bio&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;bo&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f12700f2-fe05-4f4c-8e6f-fc590522ada1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yc bh bf bi yd ye yf yg by jo yh gk yj m</value>
      <webElementGuid>ce5250af-c0e2-429a-9982-0b5e66124207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b23c4355-427a-405c-85e2-f45ca759882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bio</value>
      <webElementGuid>b1e9b15f-71e5-414a-adc7-3b7285c872ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bo</value>
      <webElementGuid>2fc5674f-c326-4f57-b6f0-51a8d21811f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;n o p vx vy vz wa wb gc wc wd z we jy ij wf&quot;]/div[@class=&quot;jd wg wh zn wj wk&quot;]/div[@class=&quot;wl li wm wn x cf c wo wp nq wq wr ws wt&quot;]/div[@class=&quot;pt x&quot;]/span[@class=&quot;ar b bu am bx&quot;]/div[@class=&quot;m n fb&quot;]/div[@class=&quot;n m u lf li xz qr gy lr yb&quot;]/textarea[@class=&quot;yc bh bf bi yd ye yf yg by jo yh gk yj m&quot;]</value>
      <webElementGuid>a2da0d99-c189-4413-89d2-be285e9f13d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='bio']</value>
      <webElementGuid>97da5d4f-aa4f-478d-849c-60b2edef0a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short bio'])[1]/following::textarea[1]</value>
      <webElementGuid>bfb63fa9-0734-4b61-9143-2992e1fe2e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name*'])[1]/following::textarea[1]</value>
      <webElementGuid>07d78709-56aa-4881-840e-010fda727aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display a link to your X profile'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a7ae5cf6-9f52-40f0-acd5-c91670a2ae05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Page'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8c3d2c9d-f157-4908-8c0a-342ca0c9bb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bo']/parent::*</value>
      <webElementGuid>f1552917-208c-4bdd-9bf6-15d43895dbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/textarea</value>
      <webElementGuid>0f8d07e3-1cf2-41b6-a114-21ebf2e9f201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'bio' and (text() = 'bo' or . = 'bo')]</value>
      <webElementGuid>1b8656af-2ed4-422f-a736-8eeea96b8b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
