<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Write_eh by l bz ca ei n ay ej</name>
   <tag></tag>
   <elementGuidId>3893c923-ed4c-46ab-8c4c-3941c6e2bd53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div[5]/button/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.eh.by.l.bz.ca.ei.n.ay.ej</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;headerUserIcon&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c7f2829-c42a-40ba-875a-ffcaef49a8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eh by l bz ca ei n ay ej</value>
      <webElementGuid>35faab28-da25-4e28-a4bd-acdce21ca266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;l c&quot;]/div[@class=&quot;l m n o c&quot;]/div[@class=&quot;p q r ab ac&quot;]/div[@class=&quot;l&quot;]/button[@class=&quot;ay ed am ab q ao ee ef eg&quot;]/div[@class=&quot;l dq&quot;]/div[@class=&quot;l dq&quot;]/div[@class=&quot;eh by l bz ca ei n ay ej&quot;]</value>
      <webElementGuid>4027f8fc-2559-4144-a573-16d2fb36ecab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div[5]/button/div/div/div</value>
      <webElementGuid>4437767e-88f4-47de-a41d-269b071cda25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>f092715d-3a0c-46e8-b20e-530d04b97a2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
