<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Write</name>
   <tag></tag>
   <elementGuidId>3e7bb03e-8a84-40fa-a3ba-2071136855d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ar.b.bu.am.ao.cf.cg.n.o.ch.ci</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;headerWriteButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5482d963-f9f0-4932-9937-78b7a696557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ar b bu am ao cf cg n o ch ci</value>
      <webElementGuid>74ccd408-a1f9-4886-98f0-1acbb8c11665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Write</value>
      <webElementGuid>952d2214-682a-4a03-85ba-d0e485a3a1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;a b c&quot;]/div[@class=&quot;x c&quot;]/div[@class=&quot;x y z ab c&quot;]/div[@class=&quot;bb o ae n bc&quot;]/div[@class=&quot;h k aj cc cd&quot;]/div[@class=&quot;ce n&quot;]/a[@class=&quot;be ap bf bg bh as bi ac at au av aw ax ay az&quot;]/div[@class=&quot;ar b bu am ao cf cg n o ch ci&quot;]</value>
      <webElementGuid>655602cd-463d-4946-8508-8c445bf01188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div/a/div</value>
      <webElementGuid>4607ffea-ff33-4071-845a-321bd29f12a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in app'])[1]/following::div[9]</value>
      <webElementGuid>f39017a5-daaf-4deb-9a3a-f8b52d491e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get unlimited access to the best of Medium for less than $1/week.'])[1]/preceding::div[12]</value>
      <webElementGuid>21978f81-4b6b-49b3-bf26-ff6f25cd45f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>c00a1569-b087-43f5-a836-6f1bac295d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Write' or . = 'Write')]</value>
      <webElementGuid>2a554351-f6a8-4613-997d-c76374d13ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
