<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flutter</name>
   <tag></tag>
   <elementGuidId>dd2e33fa-3222-482f-891c-e34cbb2ab1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResults']/div/ul/div[6]/li/a/div/div[2]/div/div/span/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Flutter&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>043ba58f-eec0-4542-a23c-d777244bbc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x rs rt gm gk ld</value>
      <webElementGuid>0e5d3c1f-3b07-4e92-9145-72031542f579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flutter</value>
      <webElementGuid>321903d9-51f0-42ae-a34b-0de8c8de602a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResults&quot;)/div[@class=&quot;qz x&quot;]/ul[@class=&quot;rh ri n rb fb&quot;]/div[@class=&quot;rr x&quot;]/li[@class=&quot;ru rv dw n&quot;]/a[@class=&quot;be ap bf bg bh as bi ac at au av aw ax ay az&quot;]/div[@class=&quot;o n&quot;]/div[@class=&quot;an m x&quot;]/div[@class=&quot;n&quot;]/div[1]/span[@class=&quot;ar b bu am bx&quot;]/p[@class=&quot;ar b bu am bx&quot;]/span[@class=&quot;x rs rt gm gk ld&quot;]</value>
      <webElementGuid>97072a85-7dd9-4463-a8e2-d619a06bcbf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResults']/div/ul/div[6]/li/a/div/div[2]/div/div/span/p/span</value>
      <webElementGuid>fd9f2761-e2ec-4de1-afca-c1aaddf15af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FlutterDevs'])[1]/following::span[2]</value>
      <webElementGuid>4ee0cf84-83ad-4a8d-863f-f67872094ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flutter'])[1]/following::span[4]</value>
      <webElementGuid>2c5334ab-44ec-4ec5-bfe6-d2b4630f7bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flutter App Development'])[1]/preceding::span[1]</value>
      <webElementGuid>f9f63d9e-ccb2-4083-8991-ff4614933c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flutter Widget'])[1]/preceding::span[3]</value>
      <webElementGuid>4fb342da-d949-492a-ab5b-a7fb0f2c8d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/li/a/div/div[2]/div/div/span/p/span</value>
      <webElementGuid>cf988175-d7fa-4848-8a07-f17c724ab4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Flutter' or . = 'Flutter')]</value>
      <webElementGuid>2b9b571f-82b4-4733-a60c-90fa142a1101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
